require("config.options")
require("config.keymaps")
require("config.autocmds")

vim.pack.add({
  "https://github.com/nvim-lua/plenary.nvim",
  "https://github.com/sudo-tee/opencode.nvim",
  "https://github.com/MeanderingProgrammer/render-markdown.nvim",
  "https://github.com/nvim-telescope/telescope.nvim",
  "https://github.com/nvim-tree/nvim-web-devicons",
  "https://github.com/nvim-telescope/telescope-fzf-native.nvim",
  "https://github.com/kdheepak/lazygit.nvim",
  "https://github.com/lewis6991/gitsigns.nvim",
  "https://github.com/nvim-mini/mini.nvim",
  "https://github.com/MunifTanjim/nui.nvim",
  "https://github.com/mason-org/mason.nvim",
  "https://github.com/mason-org/mason-lspconfig.nvim",
  "https://github.com/neovim/nvim-lspconfig",
  "https://github.com/saghen/blink.cmp",
  "https://github.com/saghen/blink.indent",
  "https://github.com/stevearc/conform.nvim",
  "https://github.com/chrisgrieser/nvim-origami",
  "https://github.com/esmuellert/codediff.nvim",
  "https://github.com/mikavilpas/yazi.nvim",
  "https://github.com/sainnhe/gruvbox-material",
  "https://github.com/nvim-treesitter/nvim-treesitter",
  'https://github.com/MeanderingProgrammer/harpoon-core.nvim',
  "https://github.com/akinsho/toggleterm.nvim",
})

require("plugins.telescope").setup()
require("plugins.lazygit").setup()
require("plugins.gitsigns").setup()
require("plugins.mini").setup()
require("plugins.mason").setup()
require("plugins.blink").setup()
require("plugins.blink-indent").setup()
require("plugins.nvim-lsp").setup()
require("plugins.conform").setup()
require("plugins.origami").setup()
require("plugins.codediff").setup()
require("plugins.yazi").setup()
require("plugins.theme").setup()
require("plugins.treesitter").setup()
require("plugins.opencode").setup()
require('plugins.harpoon-core').setup()
require("plugins.toggleterm").setup()
